/*
 * Copyright (c) 2026, Delkyy
 * SPDX-License-Identifier: BSD-2-Clause
 */
package com.slayeralts;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.Map;

/**
 * Monster name -> an in-game item that depicts it.
 *
 * There is no NPC image API - NPCComposition hands you 3D model ids, not pictures. But
 * the cache is full of items that show monsters: slayer guide icons, boss pets, heads,
 * masks. ItemManager renders those out of the player's own cache, so nothing is
 * redistributed and nothing is downloaded. Core's slayer plugin picks its task icons
 * the same way.
 *
 * Generated by tools/build-icons.py. Coverage is partial on purpose - a wrong icon is
 * worse than none, so anything the matcher isn't sure about gets left out.
 */
final class Icons
{
	private static final String RESOURCE = "icons.json";

	private final Map<String, Integer> byName;

	private Icons(Map<String, Integer> byName)
	{
		this.byName = byName;
	}

	static Icons load(Gson gson)
	{
		Type type = new TypeToken<Map<String, Integer>>()
		{
		}.getType();

		try (InputStream in = Icons.class.getResourceAsStream(RESOURCE))
		{
			if (in == null)
			{
				return new Icons(Collections.emptyMap());
			}
			Map<String, Integer> m = gson.fromJson(
				new InputStreamReader(in, StandardCharsets.UTF_8), type);
			return new Icons(m == null ? Collections.emptyMap() : m);
		}
		catch (IOException e)
		{
			// icons are decoration. a missing file must not stop the panel working.
			return new Icons(Collections.emptyMap());
		}
	}

	/** Item id to draw for this monster, or -1 when we don't have one. */
	int forName(String name)
	{
		if (name == null)
		{
			return -1;
		}
		Integer id = byName.get(name);
		return id == null ? -1 : id;
	}

	int size()
	{
		return byName.size();
	}
}
