/*
 * Copyright (c) 2026, Delkyy
 * SPDX-License-Identifier: BSD-2-Clause
 */
package com.slayeralts;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.List;

/**
 * Reads the bundled task table out of the jar.
 *
 * The file is generated by tools/build-*.py off the OSRS Wiki and checked in as a
 * resource, so the plugin makes no network calls at runtime.
 */
public final class TaskData
{
	private static final String RESOURCE = "slayer-data.json";

	private static class Payload
	{
		@SerializedName("tasks")
		List<SlayerTask> tasks;
	}

	private TaskData()
	{
	}

	public static TaskBook load(Gson gson) throws IOException
	{
		try (InputStream in = TaskData.class.getResourceAsStream(RESOURCE))
		{
			if (in == null)
			{
				throw new IOException("slayer-data.json missing from the jar");
			}

			Payload p = gson.fromJson(
				new InputStreamReader(in, StandardCharsets.UTF_8), Payload.class);

			if (p == null || p.tasks == null || p.tasks.isEmpty())
			{
				throw new IOException("slayer-data.json parsed to nothing");
			}
			return new TaskBook(Collections.unmodifiableList(p.tasks));
		}
	}
}
