/*
 * Copyright (c) 2026, Delkyy
 * SPDX-License-Identifier: BSD-2-Clause
 */
package com.slayeralts;

import com.google.gson.Gson;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import org.junit.Before;
import org.junit.Test;

/**
 * The icon table is generated by a fuzzy matcher, and a wrong icon is worse than none -
 * it puts a picture of the wrong thing next to a monster and quietly misinforms.
 */
public class IconsTest
{
	private Icons icons;

	@Before
	public void setUp()
	{
		icons = Icons.load(new Gson());
	}

	@Test
	public void loadsTheTable()
	{
		assertTrue("icon table didn't load", icons.size() > 100);
	}

	@Test
	public void knownGoodIconsSurvive()
	{
		// purpose-drawn slayer guide portraits and boss pets - these should never drop
		for (String monster : new String[]{"Bloodveld", "Abyssal demon", "Nechryael",
			"Skotizo", "Vorkath", "Kraken", "Greater Demon"})
		{
			assertTrue(monster + " lost its icon", icons.forName(monster) > 0);
		}
	}

	@Test
	public void humansAreNotUsedAsMonsterPortraits()
	{
		// PICKPOCKET_GUIDE_* are generic human faces from the thieving guide. they were
		// landing on dwarves and elemental warriors: a city guard's portrait next to
		// "Black Guard", which is a dwarf. no icon is the honest answer.
		for (String monster : new String[]{"Black Guard", "Black Knights",
			"Dark warriors", "Ice warriors", "Shadow warriors"})
		{
			assertEquals(monster + " should have no icon rather than a human portrait",
				-1, icons.forName(monster));
		}
	}

	@Test
	public void fuzzyMatchingDoesNotGrabUnrelatedItems()
	{
		// matching against all 19,000 items turned "Black bear" into BLACK_BEAD and
		// "Ice troll" into CERT_ROLL - a near-miss on a word is not a near-miss on a
		// monster. fuzzy matching is now restricted to items that depict monsters.
		assertTrue("Black bear matched a bead", icons.forName("Black bear") != 3422);
		assertTrue("Ice troll matched a certificate", icons.forName("Ice troll") != 5551);
	}
}
